/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_00.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_00</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_00.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_01.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_01</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_01.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_02.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_02</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_02.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_03.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_03</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_03.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_04.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_04</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_04.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_05.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_05</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_05.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_06.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_06</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_06.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_07.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_07</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_07.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_08.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_08</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_08.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_09.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_09</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_09.xml</okfilename><timetvl>10</timetvl>" &

/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_10.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_10</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_10.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_11.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_11</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_11.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_12.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_12</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_12.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_13.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_13</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_13.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_14.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_14</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_14.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_15.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_15</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_15.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_16.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_16</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_16.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_17.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_17</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_17.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_18.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_18</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_18.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_19.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_19</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_19.xml</okfilename><timetvl>10</timetvl>" &
 
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_20.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_20</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_20.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_21.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_21</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_21.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_22.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_22</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_22.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_23.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_23</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_23.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_24.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_24</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_24.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_25.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_25</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_25.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_26.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_26</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_26.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_27.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_27</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_27.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_28.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_28</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_28.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_29.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_29</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_29.xml</okfilename><timetvl>10</timetvl>" &
 
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_30.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_30</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_30.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_31.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_31</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_31.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_32.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_32</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_32.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_33.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_33</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_33.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_34.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_34</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_34.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_35.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_35</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_35.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_36.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_36</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_36.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_37.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_37</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_37.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_38.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_38</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_38.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_39.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_39</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_39.xml</okfilename><timetvl>10</timetvl>" &

/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_40.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_40</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_40.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_41.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_41</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_41.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_42.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_42</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_42.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_43.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_43</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_43.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_44.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_44</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_44.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_45.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_45</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_45.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_46.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_46</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_46.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_47.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_47</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_47.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_48.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_48</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_48.xml</okfilename><timetvl>10</timetvl>" &
/htidc/public/bin/tcpgetfile /log/shqx/tcpgetfile_surfdata_49.log "<ip>127.0.0.1</ip><port>5010</port><ptype>1</ptype><clientpath>/data/shqx/sdata/surfdata_49</clientpath><srvpath>/data/shqx/tcp/surfdata</srvpath><srvpathbak>/data/shqx/tcp/surfdatabak</srvpathbak><andchild>true</andchild><matchname>SURF_*.TXT,*.DAT</matchname><okfilename>/data/shqx/tcplist/tcpgetfile_surfdata_49.xml</okfilename><timetvl>10</timetvl>" &

